name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v2
      - name: Update pod repo
        run: pod repo update
      - name: Test
        run: echo hello world
